(in-package :thierry-technologies.com/2010/06/gene-gcs)

(defun make-point-based-crossover (size system cross-points-source)
  (let ((start (* size (gcs-phenotype-length system))))
    (lambda (genome1 genome2)
      (named-let rec ((pos start)
		      (points (funcall cross-points-source))
		      (child1 0)
		      (child2 0))
	(if points
	    (let* ((next (first points))
		   (bytespec (byte (- pos next) next)))
	      (rec next (rest points)
		   (dpb (ldb bytespec genome1) bytespec child2)
		   (dpb (ldb bytespec genome2) bytespec child1)))
	    (values child1 child2))))))
