--- !ditz.rubyforge.org,2008-03-06/project 
name: Genetic GCS solver
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Genetic GCS solver
- !ditz.rubyforge.org,2008-03-06/component 
  name: Genetic algorithm
- !ditz.rubyforge.org,2008-03-06/component 
  name: Configuration parser
releases: []

